
name: 'bgis_edw_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  database: false
  schema: false
  identifier: false

seeds:
  bgis_edw_dbt:
    +enabled: true
    +schema: ods
    # This configures data/lease_client_flag.csv
    lease_exclude_client:
      +alias: csv__lease_exclude_client
      +column_types:
        client_id: number

    # This configures data/pds_client.csv
    pds_include_client:
      +alias: csv__pds_include_client
      +column_types:
        client_id: number

models:
  +transient: true
  +sql_header: "alter session set timezone ='America/Toronto';"

  bgis_edw_dbt:
      staging:
        +materialized: view
        +schema: ods

      marts:
        +materialized: table
        +transient: false
        +schema: edw

        core:
          intermediate:
            +materialized: view
            +schema: stage

        asset:
          intermediate:
            +materialized: view
            +schema: stage

        


