
name: 'bgis_edw_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  database: false
  schema: false
  identifier: false

seeds:
  bgis_edw_dbt:
    +enabled: true
    +schema: stage
    # Thi configures data/lease_client.csv
    lease_client:
      +alias: lease_client
      +column_types:
        client_id: number

    pds_client:
      +alias: pds_client
      +column_types:
        client_id: number

models:
  +transient: true
  +sql_header: "alter session set timezone ='America/Toronto';"

  bgis_edw_dbt:
      staging:
        realsuite:
          +materialized: view
          +schema: stage
        mdm:
          +materialized: view
          +schema: stage


      marts:
        core:
          +materialized: incremental
          +schema: edw

          intermediate:
            +materialized: view
            +schema: stage


        


