with source as (
    select * from {{ source('realsuite', 'equipment') }}
),

renamed as (
    select
        equipment_id,
        eqnum,
        ifnull(client_eqnum,'N/A') as client_eqnum,
        client_id,
        parent,
        serialnum,
        assetnum,
        building_id,
        description,
        vendor,
        vendor_id,
        po_id,
        invoice_id,
        cost_code,
        failurecode,
        manufacturer,
        date(installdate) as install_date,
        date(warrantyexpdate) as warrantyexp_date,
        meterreading,
        avgmeterunit,
        totalcost,
        ytdcost,
        budgetcost,
        classification,
        calnum,
        isrunning,
        itemnum,
        date(readingdate) as reading_date,
        unchargedcost,
        totunchargedcost,
        totdowntime,
        sbit,
        date(statusdate) as statusdate,
        eq1,
        eq2,
        eq3,
        eq4,
        eq5,
        eq6,
        eq7,
        eq8,
        eq9,
        eq10,
        eq11,
        eq12,
        eq13,
        eq14,
        eq15,
        eq16,
        eq17,
        eq18,
        eq19,
        eq20,
        eq21,
        eq22,
        eq23,
        eq24,
        ldkey,
        meterreading2,
        avgmeterunit2,
        meterlabel1,
        meterlabel2,
        elemental_classification,
        meterunit1,
        meterunit2,
        date(readingdate2) as reading2_date,
        priority,
        invcost,
        glaccount,
        rotsuspacct,
        children,
        binnum,
        disabled,
        classstructureid,
        inheritmeter1chang,
        inheritmeter2chang,
        meter1weightprcnt,
        meter2weightprcnt,
        importdeltameter1,
        importdeltameter2,
        abi_code,
        roof_serfacetype,
        lock_type,
        ceiling_type,
        floor_type,
        frame_type,
        alarm_company,
        alarm_systemno,
        vcr_make,
        display_colour,
        switcher_make,
        switcher_model,
        heat_primaryfuel,
        light_type,
        hvac_tonnage,
        meter_verified,
        utility_type,
        meter_type,
        bluebox_participation,
        unit_count,
        storagetank_location,
        storagetank_capacity,
        storagetank_capunit,
        criticality_code,
        env_substance,
        exterior_wall_type,
        interior_wall_type,
        wall_finish,
        ownership,
        date(purchasedate) as purchase_date,
        estimateservicelife,
        certificate_expiry,
        converted,
        category_id,
        systemtype_id,
        eqtype_id,
        inactive,
        date(inactivatedon) as inactivated_date,
        inactivatedby,
        rowstamp,
        external_key,
        maintenance_responsibility,
        application_source,
        purchaseprice,
        replacecost,
        ctx_fulltext,
        parent_equipment_id,
        fr_description,
        acquisition_status_code,
        date(acquisition_status_date) as acquisition_status_date,
        disposition_status_code,
        date(disposition_status_date) as disposition_status_date,
        eq_code_cross_ref,
        eq_code_cross_ref_id,
        location,
        total_tax,
        total_gst,
        vendor_name,
        date(service_removal_date) as service_removal_date,
        date(planned_decomissioned_date) as planned_decomissioned_date,
        date(actual_decomissioned_date) as actual_decomissioned_date,
        regulated_building_item,
        upper(status) as status,
        isasset,
        ismaintainable,
        isquestionnaire,
        building_item_zone_id,
        date(labourwarrantyexpdate) as labourwarrantyexp_date,
        date(manufactureddate) as manufactured_date,
        modelname,
        conditionrating,
        legionella,
        heritage,
        detail1,
        detail2,
        detail3,
        detail4,
        detail5,
        detail6,
        detail7,
        detail8,
        detail9,
        detail10,
        detail11,
        detail12,
        detail13,
        detail14,
        detail15,
        detail16,
        detail17,
        detail18,
        detail19,
        detail20,
        detail21,
        detail22,
        detail23,
        detail24,
        detail25,
        detail26,
        detail27,
        detail28,
        detail29,
        detail30,
        barcode_type,
        old_eqtype_id,
        old_eqnum,
        old_equipment_id,
        area_id,
        bit_id,
        charge_to_account,
        contract_approval_number,
        contract_details,
        contract_number,
        contract_status,
        curr_st_id,
        floor_id,
        date(keydate) as key_date,
        pm_responsibility,
        pm_responsibility_comment,
        date(seasonalstartdate) as seasonalstart_date,
        date(seasonalenddate) as seasonalend_date,
        special_instructions,
        date(startdate) as start_date,
        {{ rs_audit_cols(source('realsuite', 'equipment')) }},
        {{ cdc_audit_cols(source('realsuite', 'equipment')) }}
    from source
)

select * from renamed